add_newline = false

format = """
$username$time$git_branch$directory$battery
$character
"""

[character]
success_symbol = "[❯❯](#d89eff)"
error_symbol = "[❯❯](#ffa6cb)"

[directory]
truncation_length = 5
truncation_symbol = "…/"
format = "[$path]($style)[$read_only]($read_only_style) "
style = "#c4c8ff"
read_only = "  "
home_symbol = "~"

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 30
style = "#d2adff"

[git_branch]
disabled = false
format = "[$symbol$branch ]($style)"
symbol = "  "
style = "#ffd5a1"

[time]
disabled = true
format = " 🍋 [$time]($style)"
time_format = "%I:%M %p"
use_12hr = true
style = "#ffdaad"

[username]
disabled = false
format = "[$user]($style) "
style_user = "#9cc8ff"
show_always = true
